"""Compare an isolated Open WebUI SQLite schema with the exact runtime model.

This helper never opens the source database for writes and never stamps an
Alembic revision.  A successful report only proves structural parity with the
installed 0.11.2 metadata; the operator must still review data transformations
before setting the launcher's baseline marker.
"""

from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path
import shutil
import sqlite3
import sys


def snapshot(path: str | Path) -> dict:
    db = sqlite3.connect(path)
    try:
        tables = []
        for row in db.execute("SELECT type,name,sql FROM sqlite_master WHERE type IN ('table','index','trigger','view') AND name NOT LIKE 'sqlite_%' ORDER BY type,name"):
            tables.append({"type": row[0], "name": row[1], "sql": row[2]})
        return {"path": str(path), "objects": tables, "sha256": hashlib.sha256(json.dumps(tables, ensure_ascii=False, sort_keys=True).encode()).hexdigest(), "quick_check": db.execute("PRAGMA quick_check").fetchone()[0]}
    finally:
        db.close()


def main() -> None:  # pragma: no cover - portable maintenance command
    parser = argparse.ArgumentParser()
    parser.add_argument("--source-db", required=True)
    parser.add_argument("--clean-db", required=True)
    parser.add_argument("--output", required=True)
    args = parser.parse_args()
    source = Path(args.source_db); clean = Path(args.clean_db)
    if not source.exists():
        raise SystemExit("source database does not exist")
    # The clean database must have been generated by the exact runtime's
    # official metadata/migration procedure.  Do not generate or mutate it in
    # this comparison command.
    result = {"source": snapshot(source), "clean": snapshot(clean) if clean.exists() else None, "match": False, "migration_history_written": False}
    if result["clean"]:
        result["match"] = result["source"]["sha256"] == result["clean"]["sha256"]
    Path(args.output).write_text(json.dumps(result, ensure_ascii=False, indent=2), encoding="utf-8")
    print(json.dumps({"match": result["match"], "source_sha256": result["source"]["sha256"], "clean_sha256": result["clean"]["sha256"] if result["clean"] else None}, ensure_ascii=False))
    if not result["match"]:
        raise SystemExit(2)


if __name__ == "__main__":
    main()
