[CmdletBinding()]
param(
  [Parameter(Mandatory=$true)][string]$SourceDatabase,
  [Parameter(Mandatory=$true)][string]$CleanDatabase,
  [string]$Output = (Join-Path $PSScriptRoot '..\migration-rehearsal.json'),
  [string]$Python = $env:CLASSROOM_PYTHON
)
$ErrorActionPreference = 'Stop'
$bundleRoot=(Resolve-Path (Join-Path $PSScriptRoot '..')).Path
$projectRoot=(Resolve-Path (Join-Path $PSScriptRoot '..\..')).Path
$appRoot=Join-Path $bundleRoot 'app'
if(-not $Python){$Python=Join-Path $bundleRoot 'runtime\python\python.exe'}
if(-not (Test-Path $Python)){$Python=Join-Path $projectRoot 'dist\openwebui-classroom-review-windows-x64\runtime\python\python.exe'}
$env:PYTHONPATH=$appRoot
if(-not (Test-Path $CleanDatabase)){throw 'Provide a clean schema database generated by the exact Open WebUI runtime; this command will not stamp one.'}
& $Python (Join-Path $appRoot 'owui_schema_rehearse.py') --source-db $SourceDatabase --clean-db $CleanDatabase --output $Output
if($LASTEXITCODE -ne 0){throw "Open WebUI schema mismatch; student launch remains blocked ($LASTEXITCODE)."}
Write-Output "Schema rehearsal matched. Review $Output and set CLASSROOM_OPENWEBUI_MIGRATION_BASELINE=verified only after data migration review."
